-- What people actually did, so the owner panel can say more than how many
-- accounts exist.
--
-- TWO TABLES, NOT ONE. A session is a visit: who, from where, on which build.
-- An event is one thing that happened inside it. Kept apart because a visit is
-- written once and updated as it goes, while events only ever accumulate, and
-- a single wide table would have to rewrite the whole row to append a step.
--
-- NOBODY CAN WRITE THIS FROM A BROWSER. There are no insert policies at all,
-- deliberately: with row level security on and nothing granted, the anon and
-- authenticated roles cannot add a row. Everything is written by /api/track
-- using the service role, which is also the only place that can see the
-- caller's IP address. A table the public can insert into is a table the
-- public will fill with whatever it likes.

create table if not exists public.analytics_sessions (
  -- Generated by the browser so events can be attributed before any round
  -- trip has come back, and so a reload continues a visit rather than
  -- starting a second one.
  id          uuid        primary key,
  started_at  timestamptz not null default now(),
  last_at     timestamptz not null default now(),
  ip          text,
  country     text,
  -- Set once somebody signs in during the visit. The address is copied rather
  -- than joined: auth.users is not reachable over the REST API, and the whole
  -- point of the by-address view is reading the two together.
  user_id     uuid        references auth.users (id) on delete set null,
  email       text,
  build       text,
  mobile      boolean,
  referrer    text,
  events      integer     not null default 0,
  constraint analytics_ip_len       check (ip is null or char_length(ip) <= 64),
  constraint analytics_country_len  check (country is null or char_length(country) <= 8),
  constraint analytics_referrer_len check (referrer is null or char_length(referrer) <= 300)
);

create table if not exists public.analytics_events (
  id         bigint      generated always as identity primary key,
  session_id uuid        not null references public.analytics_sessions (id) on delete cascade,
  at         timestamptz not null default now(),
  name       text        not null,
  detail     text,
  constraint analytics_event_name_len   check (char_length(name) <= 40),
  constraint analytics_event_detail_len check (detail is null or char_length(detail) <= 120)
);

create index if not exists analytics_sessions_last_idx on public.analytics_sessions (last_at desc);
create index if not exists analytics_sessions_ip_idx   on public.analytics_sessions (ip, last_at desc);
create index if not exists analytics_events_session_idx on public.analytics_events (session_id, at);

alter table public.analytics_sessions enable row level security;
alter table public.analytics_events   enable row level security;

-- Reading is an owner's privilege, checked by the database rather than by the
-- page that draws the charts.
drop policy if exists "admin reads sessions" on public.analytics_sessions;
create policy "admin reads sessions" on public.analytics_sessions
  for select using (public.is_admin());

drop policy if exists "admin reads events" on public.analytics_events;
create policy "admin reads events" on public.analytics_events
  for select using (public.is_admin());

-- ── keeping it for a while, not forever ──────────────────────────────────
-- An IP address is personal data and the privacy policy says ninety days, so
-- something has to make that true. Called from the track endpoint on a
-- sampled basis rather than scheduled, because a cron job is one more thing
-- to remember to set up and this runs wherever traffic does.
create or replace function public.prune_analytics()
returns void
language sql
security definer
set search_path = ''
as $$
  delete from public.analytics_sessions where last_at < now() - interval '90 days';
$$;

revoke all on function public.prune_analytics() from public, anon, authenticated;
